version: "3.8"
services:
  temperrest:
    image: ghcr.io/chadhutchins182/temper-rest:main
    container_name: temperrest
    tty: true
    devices:
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
    ports:
      - 5000:5000
