name: Docker Build Only

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image id
        run: echo "IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

      - name: Test image id
        run: echo $IMAGE_ID

      - name: Build the Docker image
        run: | 
          IMAGE_ID=$(echo ghcr.io/${{ github.repository }} | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          docker build . --file Dockerfile --tag $IMAGE_ID:$(date +%s)

      - name: Container image scan
        uses: Azure/container-scan@v0.1
        with:
          image-name: $IMAGE_ID:$(date +%s)

